name: attendance-system
channels:
  - conda-forge
dependencies:
  - python=3.7
  - csvkit
  - numpy
  - opencv
  - pandas
  - pillow
  - pyfiglet
  - flask
  - requests
  - flask-cors
  - flask-restful
  - flask-uploads
  - flask-sqlalchemy
  - flask-jwt-extended
  - flask-marshmallow
  - marshmallow
  - marshmallow-sqlalchemy
  - python-dotenv